# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:

  encoders:
      Symfony\Component\Security\Core\User\User: plaintext
      AppBundle\Entity\User:
          algorithm: sha1
          iterations: 1
          encode_as_base64: false

  role_hierarchy:
          ROLE_USERS: ROLE_USER
          ROLE_ADMIN: [ROLE_USER, ROLE_USERS]

  providers:
      our_db_provider:
          entity:
              class: AppBundle:User
              property: mail

  firewalls:
      main:
          pattern:    ^/
          anonymous: true
          provider: our_db_provider
          form_login:
              login_path: login
              check_path: login_check
          logout:
              path:   logout
              target: /
